<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="AlmacenServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/AlmacenServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/AlmacenServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://almacen.webservice.adictosaltrabajo.com/">
    <import location="http://148.205.199.131:43800/TiendaElectronica/AlmacenService?WSDL" namespace="http://almacen.webservice.adictosaltrabajo.com/"/>
    <plnk:partnerLinkType name="AlmacenLinkType">
        <plnk:role name="AlmacenRole" portType="ns:Almacen"/>
    </plnk:partnerLinkType>
</definitions>
