<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="EnvioPaquetesServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/EnvioPaquetesServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/EnvioPaquetesServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://mensajeria.webservice.adictosaltrabajo.com/">
    <import location="ServicioMensajeria/localhost_8080/MensajeriaExpress/EnvioPaquetesService.wsdl" namespace="http://mensajeria.webservice.adictosaltrabajo.com/"/>
    <plnk:partnerLinkType name="EnvioPaquetesLinkType">
        <plnk:role name="EnvioPaquetesRole" portType="ns:EnvioPaquetes"/>
    </plnk:partnerLinkType>
</definitions>
